[tool.poetry]
name = "exact-rag"
version = "0.1.0"
description = "AI-augmented, conversation information retrieval and data exploration"
authors = ["Marco Franzon <marco.franzon@exact-lab.it>", "Matteo Poggi <matteo.poggi@exact-lab.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.108.0"
langchain = "^0.1.0"
toml = "^0.10.2"
openai = "^1.7.0"
langchain-openai = "^0.0.2"
chromadb = "^0.4.22"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
